# Merging & Joining Data

Often, data is split across multiple tables or files. Pandas lets you **combine** them just like SQL — or even more flexibly!

---

## Sample DataFrames

```python
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})
```

---

## Merge Like SQL: `pd.merge()`

### Inner Join (default)

```python
pd.merge(employees, departments, on="DeptID")
```

Returns only matching DeptIDs:

| EmpID | Name    | DeptID | DeptName    |
|--------|---------|--------|-------------|
| 1      | Alice   | 10     | HR          |
| 2      | Bob     | 20     | Engineering |

---

### Left Join

```python
pd.merge(employees, departments, on="DeptID", how="left")
```

Keeps all employees, fills `NaN` where no match.

---

### Right Join

```python
pd.merge(employees, departments, on="DeptID", how="right")
```

Keeps all departments, even if no employee.

---

### Outer Join

```python
pd.merge(employees, departments, on="DeptID", how="outer")
```

Includes *all* data, fills missing with `NaN`.


---

## Concatenating DataFrames

Use `pd.concat()` to **stack** datasets either vertically or horizontally.

### Vertical (rows)

```python
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})

pd.concat([df1, df2])
```

### Horizontal (columns)

```python
df1 = pd.DataFrame({"ID": [1, 2]})
df2 = pd.DataFrame({"Score": [90, 80]})

pd.concat([df1, df2], axis=1)
```

> Make sure indexes align when using `axis=1`

---

## When to Use What?

| Use Case                        | Method     |
|---------------------------------|------------|
| SQL-style joins (merge keys)    | `pd.merge()` or `.join()` |
| Stack datasets vertically       | `pd.concat([df1, df2])`   |
| Combine different features side-by-side | `pd.concat([df1, df2], axis=1)` |
| Align on index                 | `.join()` or merge with `right_index=True` |

---

## Summary

- Use `merge()` like SQL joins (`inner`, `left`, `right`, `outer`)  
- Use `concat()` to stack DataFrames (rows or columns)  
- Handle mismatched keys and indexes with care  
- Merging and joining are essential for real-world projects

In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

In [3]:
departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [4]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [5]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [8]:
pd.merge(employees, departments, on="DeptID") # inner join

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [9]:
pd.merge(employees, departments, on="DeptID", how="left") #left join

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [10]:
pd.merge(employees, departments, on="DeptID", how="right") #right join

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [11]:
pd.merge(employees, departments, on="DeptID", how="outer") #outer join

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [19]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"], "Score": [673, 679]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"], "Age": [32, 40]})

In [20]:
df1

    Name  Score
0  Alice    673
1    Bob    679

In [21]:
df2

      Name  Age
0  Charlie   32
1    David   40

In [22]:
pd.concat([df1, df2])

      Name  Score   Age
0    Alice  673.0   NaN
1      Bob  679.0   NaN
0  Charlie    NaN  32.0
1    David    NaN  40.0

In [23]:
pd.concat([df1, df2], axis=1)

    Name  Score     Name  Age
0  Alice    673  Charlie   32
1    Bob    679    David   40